name: Deploy Front to Heroku.

on:
  push: 
    branches:
      - main
      - Build/Docker-container
  pull_request:
    branches:
      - main

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
      - uses: actions/checkout@v3

      - name: Change Working Directory
        run: cd corvuscoraxclient

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./corvuscoraxclient/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./corvuscoraxclient

      - name: Build the app
        run: npm run build
        working-directory: ./corvuscoraxclient

      - name: Set image tag in environment file
        run: echo "IMAGE_TAG=baszarinhi9816/corvuscoraxtest:latest" >> $GITHUB_ENV

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./corvuscoraxclient # Specify the context as your app's directory
          file: ./corvuscoraxclient/Dockerfile # Specify path to your Dockerfile
          push: true # Push the image to Docker Hub
          tags: ${{ env.IMAGE_TAG }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} # Use a secure password secret   
    
      - name: Build + Deploy to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile: Dockerfile
          process_type: web